config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'kittens#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :kittens

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord

  def as_json(options = {})
    {
      :id => self.id,
      :name => self.name,
      :age => self.age
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render :json => @kittens}
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @kitten}
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:notice] = "You have successfully created a new kitten!"
      redirect_to @kitten
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      flash[:notice] = "You have successfully edited #{@kitten.name}"
      redirect_to @kitten
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    flash[:notice] = "You have successfully destroyed #{@kitten.name}"
    redirect_to root_path
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: kitten do |f| %>
  <div>
    <% kitten.errors.full_messages_for(:name).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
    <%= f.label :name  %>
    <%= f.text_field :name %>
  </div>

  <div>
    <% kitten.errors.full_messages_for(:age).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
    <%= f.label :age %>
    <%= f.number_field :age%>
  </div>

  <div>
    <% kitten.errors.full_messages_for(:cuteness).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
    <%= f.label :cuteness %>
    <%= f.number_field :cuteness, in: 1..10%>
  </div>

  <div>
    <% kitten.errors.full_messages_for(:softness).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
    <%= f.label :softness %>
    <%= f.number_field :softness, in: 1..10 %>
  </div>

  <%= f.submit %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit <%= @kitten.name %></h1>

<%= render 'form', kitten: @kitten%>
<%= link_to 'Delete', kitten_path(@kitten), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<ul>
  <% @kittens.each do |kitten| %>
  <li>
    <h3><%= link_to kitten.name, kitten_path(kitten) %></h3>
    <ul>
      <li> Age: <%= kitten.age %></li>
      <li>Cuteness: <%= kitten.cuteness %></li>
      <li> Softness: <%= kitten.softness %></li>
    </ul>
  </li>

  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1>Create a Kitten!</h1>

<%= render 'form', kitten: @kitten %>

app/views/kittens/show.html.erb
<h1>This is <%= @kitten.name %>!</h1>

<p>
  <%= @kitten.name %> is <%= @kitten.age %> years old! Also look at this...
  <%= @kitten.name %> has a cuteness level of <%= @kitten.cuteness %> and a
  softness level of <%= @kitten.softness %>. Wow!
</p>

<%= link_to 'Edit', edit_kitten_path(@kitten) %>
<%= link_to 'Delete', kitten_path(@kitten), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <%= link_to 'Home', root_path %>
      <%= link_to 'New Kitten', new_kitten_path %>
    </div>

    <div>
      <%= flash[:notice] if flash[:notice] %>
    </div>
    <%= yield %>
  </body>
</html>